apiVersion: v1
kind: Namespace
metadata:
  name: cloud

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud
  namespace: cloud

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloud-role-bindding
subjects:
  - kind: ServiceAccount
    name: cloud
    namespace: cloud
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-deploy
  namespace: cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud
  template:
    metadata:
      labels:
        app: cloud
    serviceAccountName: cloud
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
        nodeName: "u1"
      containers:
      - name: cloud
        image: luangeng/cloud
        imagePullPolicy: IfNotPresent
        env:
        - name: TEST
          value: "test"
        ports:
        - containerPort: 80
      
---

apiVersion: v1
kind: Service
metadata:
  name: cloud
  namespace: cloud
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30180
  selector:
    app: cloud

